version: '3.8'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: magic-battle
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

  app:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "yarn install && yarn start"
    ports:
      - 3000:3000
    depends_on:
      - mongo
